# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoSmokingPeople' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'KYDrawerController'
  pod 'Alamofire', '~> 4.5' 
  pod 'Toaster'
  pod 'JTAppleCalendar', '~> 7.0'
  # Pods for NoSmokingPeople

end
