# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoSmokingPeople' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'KYDrawerController'
  # Pods for NoSmokingPeople

  target 'NoSmokingPeopleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoSmokingPeopleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
